server:
  port: 8081
  servlet:
    context-path: /backend

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

oss:
  qiniu:
    imagesDomain: http://qvpa4kdg1.hb-bkt.clouddn.com
    videosDomain: http://qvr0ra1yr.hb-bkt.clouddn.com
    accessKey: ErQyzBv_tvi2WDbTCvM1KqzQQWG6eAHzKot7JXGj
    secretKey: qG7OJIdt7ZY0PlRXPn1-N3pBgXIXgnlUIM4Ha_UB
    imagesBucketName: source-code-in-product-images
    videosBucketName: source-code-in-product-videos



spring:
  profiles:
    active: dev        # 激活环境配置
  servlet:
    multipart:
      enabled: true   #是否启用http上传处理
      max-request-size:  500MB  #最大请求文件的大小
      max-file-size: 100MB #设置单个文件最大长度
      file-size-threshold: 50MB #当文件达到多少时进行磁盘写入
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # 日期格式


